-- ROLES
INSERT INTO ROLES (name) VALUES
  ("Admin"),
  ("Cliente");

-- COUNTRIES (195 estados soberanos reconocidos: 193 miembros ONU + Vaticano + Palestina)
INSERT INTO COUNTRIES (name, iso_code) VALUES
  ('Afghanistan', 'AF'),
  ('Albania', 'AL'),
  ('Algeria', 'DZ'),
  ('Andorra', 'AD'),
  ('Angola', 'AO'),
  ('Antigua and Barbuda', 'AG'),
  ('Argentina', 'AR'),
  ('Armenia', 'AM'),
  ('Australia', 'AU'),
  ('Austria', 'AT'),
  ('Azerbaijan', 'AZ'),
  ('Bahamas', 'BS'),
  ('Bahrain', 'BH'),
  ('Bangladesh', 'BD'),
  ('Barbados', 'BB'),
  ('Belarus', 'BY'),
  ('Belgium', 'BE'),
  ('Belize', 'BZ'),
  ('Benin', 'BJ'),
  ('Bhutan', 'BT'),
  ('Bolivia', 'BO'),
  ('Bosnia and Herzegovina', 'BA'),
  ('Botswana', 'BW'),
  ('Brazil', 'BR'),
  ('Brunei', 'BN'),
  ('Bulgaria', 'BG'),
  ('Burkina Faso', 'BF'),
  ('Burundi', 'BI'),
  ('Cabo Verde', 'CV'),
  ('Cambodia', 'KH'),
  ('Cameroon', 'CM'),
  ('Canada', 'CA'),
  ('Central African Republic', 'CF'),
  ('Chad', 'TD'),
  ('Chile', 'CL'),
  ('China', 'CN'),
  ('Colombia', 'CO'),
  ('Comoros', 'KM'),
  ('Congo', 'CG'),
  ('Costa Rica', 'CR'),
  ('Croatia', 'HR'),
  ('Cuba', 'CU'),
  ('Cyprus', 'CY'),
  ('Czechia', 'CZ'),
  ('Democratic Republic of the Congo', 'CD'),
  ('Denmark', 'DK'),
  ('Djibouti', 'DJ'),
  ('Dominica', 'DM'),
  ('Dominican Republic', 'DO'),
  ('Ecuador', 'EC'),
  ('Egypt', 'EG'),
  ('El Salvador', 'SV'),
  ('Equatorial Guinea', 'GQ'),
  ('Eritrea', 'ER'),
  ('Estonia', 'EE'),
  ('Eswatini', 'SZ'),
  ('Ethiopia', 'ET'),
  ('Fiji', 'FJ'),
  ('Finland', 'FI'),
  ('France', 'FR'),
  ('Gabon', 'GA'),
  ('Gambia', 'GM'),
  ('Georgia', 'GE'),
  ('Germany', 'DE'),
  ('Ghana', 'GH'),
  ('Greece', 'GR'),
  ('Grenada', 'GD'),
  ('Guatemala', 'GT'),
  ('Guinea', 'GN'),
  ('Guinea-Bissau', 'GW'),
  ('Guyana', 'GY'),
  ('Haiti', 'HT'),
  ('Honduras', 'HN'),
  ('Hungary', 'HU'),
  ('Iceland', 'IS'),
  ('India', 'IN'),
  ('Indonesia', 'ID'),
  ('Iran', 'IR'),
  ('Iraq', 'IQ'),
  ('Ireland', 'IE'),
  ('Israel', 'IL'),
  ('Italy', 'IT'),
  ('Ivory Coast', 'CI'),
  ('Jamaica', 'JM'),
  ('Japan', 'JP'),
  ('Jordan', 'JO'),
  ('Kazakhstan', 'KZ'),
  ('Kenya', 'KE'),
  ('Kiribati', 'KI'),
  ('Kuwait', 'KW'),
  ('Kyrgyzstan', 'KG'),
  ('Laos', 'LA'),
  ('Latvia', 'LV'),
  ('Lebanon', 'LB'),
  ('Lesotho', 'LS'),
  ('Liberia', 'LR'),
  ('Libya', 'LY'),
  ('Liechtenstein', 'LI'),
  ('Lithuania', 'LT'),
  ('Luxembourg', 'LU'),
  ('Madagascar', 'MG'),
  ('Malawi', 'MW'),
  ('Malaysia', 'MY'),
  ('Maldives', 'MV'),
  ('Mali', 'ML'),
  ('Malta', 'MT'),
  ('Marshall Islands', 'MH'),
  ('Mauritania', 'MR'),
  ('Mauritius', 'MU'),
  ('Mexico', 'MX'),
  ('Micronesia', 'FM'),
  ('Moldova', 'MD'),
  ('Monaco', 'MC'),
  ('Mongolia', 'MN'),
  ('Montenegro', 'ME'),
  ('Morocco', 'MA'),
  ('Mozambique', 'MZ'),
  ('Myanmar', 'MM'),
  ('Namibia', 'NA'),
  ('Nauru', 'NR'),
  ('Nepal', 'NP'),
  ('Netherlands', 'NL'),
  ('New Zealand', 'NZ'),
  ('Nicaragua', 'NI'),
  ('Niger', 'NE'),
  ('Nigeria', 'NG'),
  ('North Korea', 'KP'),
  ('North Macedonia', 'MK'),
  ('Norway', 'NO'),
  ('Oman', 'OM'),
  ('Pakistan', 'PK'),
  ('Palau', 'PW'),
  ('Palestine', 'PS'),
  ('Panama', 'PA'),
  ('Papua New Guinea', 'PG'),
  ('Paraguay', 'PY'),
  ('Peru', 'PE'),
  ('Philippines', 'PH'),
  ('Poland', 'PL'),
  ('Portugal', 'PT'),
  ('Qatar', 'QA'),
  ('Romania', 'RO'),
  ('Russia', 'RU'),
  ('Rwanda', 'RW'),
  ('Saint Kitts and Nevis', 'KN'),
  ('Saint Lucia', 'LC'),
  ('Saint Vincent and the Grenadines', 'VC'),
  ('Samoa', 'WS'),
  ('San Marino', 'SM'),
  ('Sao Tome and Principe', 'ST'),
  ('Saudi Arabia', 'SA'),
  ('Senegal', 'SN'),
  ('Serbia', 'RS'),
  ('Seychelles', 'SC'),
  ('Sierra Leone', 'SL'),
  ('Singapore', 'SG'),
  ('Slovakia', 'SK'),
  ('Slovenia', 'SI'),
  ('Solomon Islands', 'SB'),
  ('Somalia', 'SO'),
  ('South Africa', 'ZA'),
  ('South Korea', 'KR'),
  ('South Sudan', 'SS'),
  ('Spain', 'ES'),
  ('Sri Lanka', 'LK'),
  ('Sudan', 'SD'),
  ('Suriname', 'SR'),
  ('Sweden', 'SE'),
  ('Switzerland', 'CH'),
  ('Syria', 'SY'),
  ('Tajikistan', 'TJ'),
  ('Tanzania', 'TZ'),
  ('Thailand', 'TH'),
  ('Timor-Leste', 'TL'),
  ('Togo', 'TG'),
  ('Tonga', 'TO'),
  ('Trinidad and Tobago', 'TT'),
  ('Tunisia', 'TN'),
  ('Turkey', 'TR'),
  ('Turkmenistan', 'TM'),
  ('Tuvalu', 'TV'),
  ('Uganda', 'UG'),
  ('Ukraine', 'UA'),
  ('United Arab Emirates', 'AE'),
  ('United Kingdom', 'GB'),
  ('United States', 'US'),
  ('Uruguay', 'UY'),
  ('Uzbekistan', 'UZ'),
  ('Vanuatu', 'VU'),
  ('Vatican City', 'VA'),
  ('Venezuela', 'VE'),
  ('Vietnam', 'VN'),
  ('Yemen', 'YE'),
  ('Zambia', 'ZM'),
  ('Zimbabwe', 'ZW');

-- PARKINGS
INSERT INTO PARKINGS (name, country_id) VALUES
  ('Parking Central', 1);

-- USERS
INSERT INTO USERS (role_id, parking_id, name, first_surname, second_surname, email, password, onboarding_completed, status) VALUES
  (1, 1, 'Juan', 'Test', 'Test', 'juanesyt7@gmail.com', '$2b$12$ZWxjTBVABd85Ux4eg3tacO7xRzdbsW8/QclK7b.7hkqZTrqohFi7.', TRUE, 2),
  (2, 1, 'Juan', 'Cliente', 'Test', 'juanalvout38@gmail.com', '$2b$12$ZWxjTBVABd85Ux4eg3tacO7xRzdbsW8/QclK7b.7hkqZTrqohFi7.', TRUE, 2);

-- VEHICLE_TYPES
INSERT INTO VEHICLE_TYPES (name) VALUES
  ('Carro'),
  ('Moto'),
  ('Camión'),
  ('Van'),
  ('Bus');

-- PLATES
INSERT INTO PLATES (parking_id, plate, vehicle_type_id) VALUES
  (1, 'ABC123', 1),
  (1, 'XYZ456', 1),
  (1, 'DEF789', 1),
  (1, 'GHI321', 1),
  (1, 'JKL654', 1),
  (1, 'MNO987', 1),
  (1, 'PQR111', 1),
  (1, 'STU222', 1),
  (1, 'VWX333', 1),
  (1, 'YZA444', 1);

-- FLOORS
INSERT INTO FLOORS (parking_id, name) VALUES
  (1, 'Piso 1'),
  (1, 'Piso 2'),
  (1, 'Piso 3');

-- SPOTS
INSERT INTO SPOTS (floor_id, spot, spot_status, vehicle_type_id) VALUES
  (1, 'A-01', 2, 1),
  (1, 'A-02', 2, 1),
  (1, 'A-03', 2, 1),
  (2, 'B-01', 2, 1),
  (2, 'B-02', 2, 1),
  (2, 'B-03', 2, 1),
  (3, 'C-01', 2, 1),
  (3, 'C-02', 2, 1),
  (3, 'C-03', 2, 1),
  (3, 'C-04', 2, 1);

-- RATES
INSERT INTO RATES (parking_id, vehicle_type_id, value) VALUES
  (1, 1, 3500.00),
  (1, 2, 2000.00),
  (1, 3, 5000.00),
  (1, 4, 4500.00),
  (1, 5, 6000.00);

-- ENTRIES
INSERT INTO ENTRIES (parking_id, plate_id, spot_id, created_at) VALUES
  (1, 1,  1,  '2026-06-01 08:00:00'),
  (1, 2,  2,  '2026-06-01 08:30:00'),
  (1, 3,  3,  '2026-06-01 09:00:00'),
  (1, 4,  4,  '2026-06-01 09:15:00'),
  (1, 5,  5,  '2026-06-01 10:00:00'),
  (1, 6,  6,  '2026-06-01 10:45:00'),
  (1, 7,  7,  '2026-06-01 11:00:00'),
  (1, 8,  8,  '2026-06-01 11:30:00'),
  (1, 9,  9,  '2026-06-01 12:00:00'),
  (1, 10, 10, '2026-06-01 12:15:00');

-- EXITS
INSERT INTO EXITS (parking_id, plate_id, created_at) VALUES
  (1, 1,  '2026-06-01 10:00:00'),
  (1, 2,  '2026-06-01 11:00:00'),
  (1, 3,  '2026-06-01 12:00:00'),
  (1, 4,  '2026-06-01 12:30:00'),
  (1, 5,  '2026-06-01 13:00:00'),
  (1, 6,  '2026-06-01 14:00:00'),
  (1, 7,  '2026-06-01 14:30:00'),
  (1, 8,  '2026-06-01 15:00:00'),
  (1, 9,  '2026-06-01 15:45:00'),
  (1, 10, '2026-06-01 16:00:00');

-- PAYMENT_METHODS
INSERT INTO PAYMENT_METHODS (name, icon) VALUES
  ("Tarjeta de credito", "credit_card"),
  ("Tarjeta de debito", "account_balance_wallet"),
  ("Efectivo", "payments"),
  ("Bitcoin", "savings");

-- PAYMENTS
INSERT INTO PAYMENTS (parking_id, plate_id, spot_id, value, created_at, payment_method_id) VALUES
  (1, 1,  1,  7000.00,  '2026-06-01 10:05:00', 1),
  (1, 2,  2,  5000.00,  '2026-06-01 11:05:00', 1),
  (1, 3,  3,  10500.00, '2026-06-01 12:05:00', 1),
  (1, 4,  4,  7000.00,  '2026-06-01 12:35:00', 1),
  (1, 5,  5,  9000.00,  '2026-06-01 13:05:00', 1),
  (1, 6,  6,  14000.00, '2026-06-01 14:05:00', 1),
  (1, 7,  7,  10500.00, '2026-06-01 14:35:00', 1),
  (1, 8,  8,  10500.00, '2026-06-01 15:05:00', 1),
  (1, 9,  9,  14000.00, '2026-06-01 15:50:00', 1),
  (1, 10, 10, 7000.00,  '2026-06-01 16:05:00', 1);